{{- if .Values.OperationsCenter.CasC.Retriever.Enabled }}
apiVersion: v1
kind: Service
metadata:
  name: casc-retriever-sidecar-svc
spec:
  selector:
    app.kubernetes.io/component: cjoc
    com.cloudbees.cje.tenant: cjoc
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.OperationsCenter.CasC.Retriever.containerPort }}
{{- end -}}    

 