{{- if and .Values.NetworkPolicy.Enabled .Values.OperationsCenter.Enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cjoc
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
{{ include "operationsCenter.podSelector" . | indent 2 }}
  ingress:
  - ports:
    - port: {{ .Values.OperationsCenter.ContainerPort }}
      protocol: TCP
    from: {{ concat (fromYamlArray (include "master.podSelectors" .)) (fromYamlArray (include "ingress.podSelectors" .)) | toYaml | nindent 4}}
  - ports:
    - port: {{ .Values.OperationsCenter.AgentListenerPort }}
      protocol: TCP
    from: {{ concat (fromYamlArray (include "master.podSelectors" .)) (fromYamlArray (include "ingress.podSelectors" .)) | toYaml | nindent 4}}
{{- if .Values.NetworkPolicy.JMXSelectors }}
  - from:
{{ toYaml .Values.NetworkPolicy.JMXSelectors | indent 4 }}
    ports:
      - port: {{ .Values.OperationsCenter.JMXPort }}
        protocol: TCP
{{- end }}
{{- end }}
