{{- if .Values.Master.Enabled -}}
{{- if .Values.Master.HighAvailabilitySupport -}}
{{- if .Values.rbac.install -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-hazelcast-discovery
  labels:
{{ include "cloudbees-core.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
{{- end -}}
{{- end -}}
{{- end -}}
