{{- if and .Values.NetworkPolicy.Enabled .Values.Hibernation.Enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: managed-master-hibernation-monitor
  labels:
    app: managed-master-hibernation-monitor
{{ include "cloudbees-core.labels" . | indent 4 }}
spec:
{{ include "hibernationMonitor.podSelector" . | indent 2 }}
  ingress:
  - ports:
    - port: 8090
      protocol: TCP
    from: {{ concat (fromYamlArray (include "master.podSelectors" .)) (fromYamlArray (include "ingress.podSelectors" .)) | toYaml | nindent 4}}
{{- end -}}
