## Argo Configs
configs:
  # General Argo CD configuration
  params:
    ## Server properties
    # -- Run server without TLS
    server.insecure: true

  cm:
    # -- Timeout to discover if a new manifests version got published to the repository
    timeout.reconciliation: 30s
    # -- Timeout to refresh application data as well as target manifests cache
    timeout.hard.reconciliation: 30s
    
    # This is to make Sync Waves work in the App of Apps pattern (https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessment-of-argoprojioapplication-crd-has-been-removed)
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs


server:
  ingress:
    # -- Enable an ingress resource for the Argo CD server
    enabled: true
    hosts:
      - argocd.local
